media:
  input: src/assets
  output: /assets
  path: src/assets
  categories: [image, video]
content:
  - name: pages
    label: Pages
    path: src/pages
    type: collection
    subfolders: false
    view:
      fields: [link_title, permalink, meta_title]
      primary: link_title
      sort: [link_order]
    fields:
      - { name: heading_text, type: string, label: Heading Text }
      - { name: heading_image, type: image, label: Heading Image }
      - { name: heading_video, type: string, label: Heading Video }
      - { name: heading_iframe, type: string, label: Heading iFrame URL }
      - { name: layout, type: string, label: Layout }
      - { name: link_order, type: number, label: Link Order }
      - { name: link_title, type: string, label: Link Title }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
      - { name: permalink, type: string, label: Permalink }
      - { name: css, type: string, label: Custom CSS }
      - { name: body, label: Body, type: code, options: { language: markdown } }
  - name: services
    label: Services
    path: src/services
    type: collection
    subfolders: false
    view:
      fields: [link_title, heading_text]
      primary: link_title
    fields:
      - { name: heading_text, type: string, label: Heading Text }
      - { name: heading_image, type: image, label: Heading Image }
      - { name: link_title, type: string, label: Link Title }
      - { name: meta_description, type: string, label: Meta Description }
      - { name: meta_title, type: string, label: Meta Title }
      - { name: snippet, type: string, label: Snippet }
      - { name: short_snippet, type: string, label: Short Snippet }
      - { name: body, label: Body, type: code, options: { language: markdown } }
  - name: testimonials
    label: Testimonials
    path: src/testimonials
    type: collection
    subfolders: false
    filename: "{order}-{primary}.md"
    view:
      fields: [name]
      primary: name
    fields:
      - { name: name, type: string, label: Name }
      - { name: body, label: Testimonial, type: code, options: { language: markdown } }